version: '3'
services:
  #databases
  clients_db:
    container_name: clients_db
    image: mongo
    restart: always
    ports:
      - 27016:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - clients_db:/data

  article_db:
    container_name: article_db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - article_db:/data

  client_db:
    container_name: client_db
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - client_db:/data
  gateway:
    container_name: gateway
    build:
      context: ./gateway
    ports:
      - 8000:8000

  front_end:
    container_name: predictiStock_front
    build:
      context: ./front
    ports:
      - 4200:80
  article_microservice:
    container_name: article_microservice
    depends_on:
      - article_db
    build:
      context: ./article
    ports:
      - 3008:3008

  users_microservice:
    container_name: users_microservice
    depends_on:
      - clients_db
    build:
      context: ./users_v2
    ports:
      - 3007:3007
  
  clients_microservice:
    container_name: clients_microservice
    depends_on:
      - client_db
    build:
      context: ./client
    ports:
      - 3006:3006
  
volumes:
  article_db:
  client_db:
  clients_db:
